name: CI
on: [push]
env:
  DOCKER_IMAGE: resume:latest
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker login / push
        run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" |docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin "${{ secrets.DOCKER_HOST }}"
           docker image tag $DOCKER_IMAGE "${{ secrets.DOCKER_HOST }}/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPOSITORY }}/$DOCKER_IMAGE"
           docker image push "${{ secrets.DOCKER_HOST }}/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPOSITORY }}/$DOCKER_IMAGE"
